source 'https://gitlab.com/liao0322/FengLeiSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'FLSubtitleMenuView_Example' do
  pod 'FLSubtitleMenuView', :path => '../'

  target 'FLSubtitleMenuView_Tests' do
    inherit! :search_paths

    
  end
end
